# Generated by Django 5.2.4 on 2025-07-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_remove_register_email_remove_register_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
