# Generated by Django 5.2.4 on 2025-07-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
