# Generated by Django 5.2.4 on 2025-07-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_alter_tasks_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
