# Generated by Django 5.2.4 on 2025-07-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_alter_tasks_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='name',
        ),
        migrations.AddField(
            model_name='tasks',
            name='ownername',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
