# Generated by Django 5.2.4 on 2025-07-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_remove_tasks_name_tasks_ownername'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='payername',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
