# Generated by Django 5.2.4 on 2025-07-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_tasks_payername'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('ownername', models.CharField(max_length=100)),
                ('payername', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
