# Generated by Django 5.2.4 on 2025-07-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0016_remove_task_ownername_remove_task_payername_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
